### ISSUE TITLE
Can't install wuggy

### ISSUE THREAD

**Issue by soliviantar** [WuggyCode/wuggy#27]
I don't know much about python or programming in general, but I can't seem to get wuggy to get installed. [This](https://gist.github.com/soliviantar/37ff5291de036d079d1b1b0967ece4b5#file-pip-install-wuggy) happens when I try the installation command.

I'm on Windows 11, python 3.12.

**Comment by brenthuisman** [comment]
The solution is to remove the unnecessarily strict versions from the requirements file.

**Comment by Zenulous** [comment]
@soliviantar @brenthuisman Thanks for letting me know: I've updated the requirements to the latest versions and made them less strict for future updates of packages / Python. Generally I like to pin versions but I admit I have not kept this repo up to date enough for that to make sense. You'll be able to install using `pip install wuggy` again. :)

**Comment by brenthuisman** [comment]
@Zenulous Just a comment from a package maintainer: versioning deps for deployments and for upstream address separate concerns. To safeguard a deployment, you will usually want to freeze on specific dependency trees, but releasing a package upstream you usually want the opposite: support the widest possible environments, so that users' deployments have the largest chance of not having conflicting requirements (because any nontrivial set of tools will run quickly into something :P). What may help you is a testing matrix, using Github Actions is quite straightforward to test both on known-good and latest versions for example.

I can now undo my softfork for [applephrase](https://github.com/brenthuisman/applephrase) :) Are you open to a PR or two that I'd need for that?

**Comment by Zenulous** [comment]
> [@Zenulous](https://github.com/Zenulous) Just a comment from a package maintainer: versioning deps for deployments and for upstream address separate concerns. To safeguard a deployment, you will usually want to freeze on specific dependency trees, but releasing a package upstream you usually want the opposite: support the widest possible environments, so that users' deployments have the largest chance of not having conflicting requirements (because any nontrivial set of tools will run quickly into something :P). What may help you is a testing matrix, using Github Actions is quite straightforward to test both on known-good and latest versions for example.
> 
> I can now undo my softfork for [applephrase](https://github.com/brenthuisman/applephrase) :) Are you open to a PR or two that I'd need for that?

Yep, you're totally correct: and it's obvious my background is in deployments rather than packages 😉 
Yes, feel free to raise PRs if you need modifications to Wuggy so you can use it directly for applephrase (cool project by the way!)
